### ISSUE TITLE
Google Cloud Storage

### ISSUE THREAD

**Issue by DrTrills** [bailabs/s3_backup#1]
Hey all,

This seems like a great app to have. My question is would changing it to support Google Cloud Storage be that different? I am not sure as I am not an expert, but it seems Google also uses Boto https://cloud.google.com/storage/docs/boto-gsutil

I'd be happy to contribute as the bulk of it seems to be either renaming modules or just changing a few API endpoints to Google. If anyone has some suggestions to point in the right direction that would be great.

Also, if this type of thing were to be created, would it be preferred to fork this for Google? Or add Google to s3 backup and have it as an option?

**Comment by ccfiel** [comment]
yes its very possible if you a PR we are welcome to merge it. Thanks for the interest
